1차완성본(실패)
SEVERE: 경로 [/0627Web01]의 컨텍스트 내의 서블릿 [jsp]을(를) 위한 Servlet.service() 호출이,
근본 원인(root cause)과 함께, 예외 [/loginAction.jsp (행: [6], 열: [0]) useBean의
class 속성을 위한 값 [user.User]은(는) 유효하지 않습니다.]을(를) 발생시켰습니다.
org.apache.jasper.JasperException: /loginAction.jsp (행: [6], 열: [0])
useBean의 class 속성을 위한 값 [user.User]은(는) 유효하지 않습니다.